# -*- coding: utf-8 -*-
"""pickle_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwbwpeHSXtOOiIrmSLBLhHq4NQzP_KGw
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

lung_cancer_data = pd.read_csv('survey_lung_cancer.csv')

lung_cancer_data.drop_duplicates()

#Label Encoding
lung_cancer_data['GENDER'] =  lung_cancer_data['GENDER'].map({'M':1,'F':0})

lung_cancer_data['LUNG_CANCER'] = lung_cancer_data['LUNG_CANCER'].map({'YES':1,'NO':0})

x = lung_cancer_data.drop(columns = 'LUNG_CANCER',axis=1)
y = lung_cancer_data['LUNG_CANCER']

X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,stratify=y, random_state=2)

model = LogisticRegression(C= 1, max_iter= 150)
model.fit(X_train,Y_train)

import pickle

pickle.dump(model, open("pickle_file_model.sav", "wb"))